# Example: show RAM usage on the right of the status bar.

set -g @plugin 'gufranco/tmux-ram-revamped'

set -g @ram_revamped_low_fg_color '#[fg=green]'
set -g @ram_revamped_medium_fg_color '#[fg=yellow]'
set -g @ram_revamped_high_fg_color '#[fg=red]'

set -g status-right '#{ram_fg_color}#{ram_icon} #{ram_percentage}#[default] '
